language: python

script:
 - pip install pipenv
 - pipenv install --system --dev
 - pipenv shell
 - nosetests
 - wget -qO- https://deb.nodesource.com/setup_10.x | bash -
 - apt-get install -y nodejs jq
 - npm i serverless@1.39.1 -g
 - npm i
 - serverless deploy -v --region $REGION
